#userModule
post_url=https://reqres.in/api/users
get_url=https://reqres.in/api/users/{user_id}
put_url=https://reqres.in/api/users/{user_id}
delete_url=https://reqres.in/api/users/{user_id}
API_Key = x-api-key
API_Value =pro_bbd554ce7c21891d4197fecd3c2a446b4e5b56cfa98600b27a5d5fd579a2a24b